### ISSUE TITLE
Small Batch is failing in production 

### ISSUE THREAD

**Issue by davidschober** [nulib/images#301]
### Descriptive summary
Small Batch is failing in production. 

Sidekiq reports:

 Include @channel I'm trying to batch import a small batch -- I am getting this message in sidekiq "RestClient::MethodNotAllowed: 405 Method Not Allowed" what does that mean?

From Logs:

Found the error:
```2016-09-22T19:07:36.907Z 8832 TID-ox44bufyk MultiresimagesBatchWorker JID-c1c6fdb63303bfc584e9bd3e INFO: start
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
2016-09-22T19:07:39.725Z 8832 TID-ox44bufyk MultiresimagesBatchWorker JID-c1c6fdb63303bfc584e9bd3e INFO: fail: 2.817 sec
2016-09-22T19:07:39.725Z 8832 TID-ox44bufyk WARN: {"class"=>"MultiresimagesBatchWorker", "args"=>["/images_dropbox/batches/11741/320606.tif"], "retry"=>true, "queue"=>"default", "jid"=>"c1c6fdb63303bfc584e9bd3e", "created_at"=>1474570649.1366792, "enqueued_at"=>1474571256.9068325, "error_message"=>"405 Method Not Allowed", "error_class"=>"RestClient::MethodNotAllowed", "failed_at"=>1474570673.6809406, "retry_count"=>5, "retried_at"=>1474571259.7247138}
2016-09-22T19:07:39.725Z 8832 TID-ox44bufyk WARN: RestClient::MethodNotAllowed: 405 Method Not Allowed
2016-09-22T19:07:39.725Z 8832 TID-ox44bufyk WARN: /var/www/dil_hydra/shared/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!'
/var/www/dil_hydra/shared/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:495:in `process_result'
/var/www/dil_hydra/shared/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:853:in `start'
/var/www/dil_hydra/shared/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
/var/www/dil_hydra/shared/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
/var/www/dil_hydra/shared/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
/var/www/dil_hydra/shared/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/resource.rb:94:in `delete'
/var/www/dil_hydra/shared/bundle/ruby/2.2.0/gems/rubydora-1.8.1/lib/rubydora/rest_api_client.rb:180:in `purge_object'
/var/www/dil_hydra/shared/bundle/ruby/2.2.0/gems/rubydora-1.8.1/lib/rubydora/repository.rb:19:in `purge_object'
/var/www/dil_hydra/shared/bundle/ruby/2.2.0/gems/rubydora-1.8.1/lib/rubydora/digital_object.rb:227:in `delete'
/var/www/dil_hydra/shared/bundle/ruby/2.2.0/gems/active-fedora-8.0.1/lib/active_fedora/persistence.rb:67:in `delete'
/var/www/dil_hydra/releases/20160920151408/app/workers/multiresimages_batch_worker.rb:31:in `rescue in perform'
### Expected behavior

### Actual behavior

### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related tickets or prior related work here.

**Comment by davidschober** [comment]
Brendan's currently investigating:


brendanquinn [2:25 PM]  
looks like sidekiq isn't running on prod :disappointed:

[2:25]  
 ```[deploy@images-p ~]$ ps -aef | grep sidekiq
deploy    3726  3642  0 14:25 pts/0    00:00:00 grep sidekiq
deploy    8832     1  1 Sep21 ?        00:25:07 sidekiq 4.1.1 dil_hydra [0 of 25 busy]     ```

new messages
[2:25]  
maybe it is?

[2:26]  
i'm going to restart sidekiq remotely to see if that does it

[2:26]  
b/c the batch just worked on images-s

[2:26]  
so it's probably not a code issue

**Comment by davidschober** [comment]
It is ingesting in staging. It's looking like it's not a code issue.

**Comment by davidschober** [comment]
@d-venckus restarted redis and sidekiq. It seems like redis ran into a JVM issue.  Working now.

**Comment by davidschober** [comment]
@d-venckus @Toputnal Can we figure out if there's a way to monitor?
